version: '3'

networks:
  web:
    external: true

services:
  katsumori-web-app:
    image: nginx
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - "8082:80"
    labels:
      - traefik.enable=true
      - traefik.backend=backend-katsumori-web-app-katsumori-web-app
      - traefik.frontend.rule=Host:katsumori.fun
      - traefik.docker.network=web
      - traefik.port=80
    networks:
      - web

  npm:
    image: node:18.4.0
    volumes:
      - .:/usr/share/nginx/html:delegated
    working_dir: /usr/share/nginx/html
    entrypoint: ['npm']
    labels:
      - traefik.enable=false